### ISSUE TITLE
Find a way to play a file that works on Windows and Linux but doesn't take too much effort

### ISSUE THREAD

**Issue by noahadvs** [redeem4/YAMA_Music_Player#16]

**Comment by redeem4** [comment]
What do you mean by this issue? Does the file that's included in the test_audio folder not work on Linux? If not, try to find a file that plays on Linux and then I can try it on Windows and test to see if it works.

**Comment by noahadvs** [comment]
The problem is "C:/asdf/foo/bar" is a windows directory and doesn't point to any location on my computer. On my computer, the directory would be "/run/media/noah/noah_hdd/noah_files/src/YAMA_Music_Player/test_audio", which wouldn't work on your computer.

**Comment by redeem4** [comment]
I believe this is a non-issue (currently). That is obviously not the permanent way we will be handling audio and that hard-coded way was just a way to test that we could make it work and when we have the file system viewer up a running; It should be much easier to deal with this issue. 

I'm going to close this issue for now unless it becomes relevant again.
